class Renderer{constructor(canvas){this._canvas=canvas;this._objects=[];this._clearColor={r:0,g:56/255,b:101/255,a:1};}
async init(){if(!navigator.gpu){throw Error("WebGPU is not supported in this browser.");}
const adapter=await navigator.gpu.requestAdapter();if(!adapter){throw Error("Couldn't request WebGPU adapter.");}
this._device=await adapter.requestDevice();this._context=this._canvas.getContext("webgpu");this._canvasFormat=navigator.gpu.getPreferredCanvasFormat();this._context.configure({device:this._device,format:this._canvasFormat,});this.resizeCanvas();window.addEventListener('resize',this.resizeCanvas.bind(this));}
resizeCanvas(){const devicePixelRatio=window.devicePixelRatio||1;const width=window.innerWidth*devicePixelRatio;const height=window.innerHeight*devicePixelRatio;this._canvas.width=width;this._canvas.height=height;this._canvas.style.width=`${window.innerWidth}px`;this._canvas.style.height=`${window.innerHeight}px`;this._canvas.style.transformOrigin="center";this.render();}
async appendSceneObject(obj){await obj.init();this._objects.push(obj);}
renderToSelectedView(outputView){for(const obj of this._objects){obj?.updateGeometry();}
let encoder=this._device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:outputView,clearValue:this._clearColor,loadOp:"clear",storeOp:"store",}]});for(const obj of this._objects){obj?.render(pass);}
pass.end();const computePass=encoder.beginComputePass();for(const obj of this._objects){obj?.compute(computePass);}
computePass.end();const commandBuffer=encoder.finish();this._device.queue.submit([commandBuffer]);}
render(){this.renderToSelectedView(this._context.getCurrentTexture().createView());}};class StandardTextObject{constructor(inputText,spacing=5,textFont='16px monospace'){this._textFont=textFont;this._lineSpacing=spacing;this._textCanvas=document.createElement('canvas');this._textContext=this._textCanvas.getContext('2d');this.updateTextRegion(inputText);this.updateText(inputText);this._textCanvas.style.position='absolute';this._textCanvas.style.top='10px';this._textCanvas.style.right='10px';this._textCanvas.style.pointerEvents='none';document.body.appendChild(this._textCanvas);}
updateTextRegion(newText){this._textContext.font=this._textFont;this._lines=newText.split('\n');this._width=Math.max(...this._lines.map(line=>this._textContext.measureText(line).width));const match=this._textFont.match(/(\d+)px/);this._fontSize=match?parseInt(match[1],10):16;this._height=this._lines.length*(this._fontSize+this._lineSpacing);this._paddingx=8;this._paddingtop=5;this._canvasWidth=Math.ceil(this._width+this._paddingx*2);this._canvasHeight=Math.ceil(this._height+this._paddingtop*2);this._textCanvas.width=this._canvasWidth;this._textCanvas.height=this._canvasHeight;this._textContext.font=this._textFont;this._textContext.textBaseline='top';}
updateText(newText){this._lines=newText.split('\n');this._textContext.font=this._textFont;const newWidth=Math.max(...this._lines.map(l=>this._textContext.measureText(l).width));if(newWidth>this._width||this._lines.length!==this._textCanvas.height/(this._fontSize+this._lineSpacing)){this.updateTextRegion(newText);}
this._textContext.clearRect(0,0,this._canvasWidth,this._canvasHeight);this._textContext.fillStyle='rgba(0, 0, 0, 0.6)';this._textContext.fillRect(0,0,this._canvasWidth,this._canvasHeight);this._textContext.fillStyle='white';this._lines.forEach((line,idx)=>{const x=this._paddingx;const y=this._paddingtop+idx*(this._fontSize+this._lineSpacing);this._textContext.fillText(line,x,y);});}
toggleVisibility(){this._textCanvas.hidden=!this._textCanvas.hidden;}
setPosition(x,y){this._textCanvas.style.right='auto';this._textCanvas.style.left=x+'px';this._textCanvas.style.top=y+'px';}};class SceneObject{static _objectCnt=0;constructor(device,canvasFormat,shaderFile){if(this.constructor==SceneObject){throw new Error("Abstract classes can't be instantiated.");}
this._device=device;this._canvasFormat=canvasFormat;this._shaderFile=shaderFile;SceneObject._objectCnt+=1;}
getName(){return this.constructor.name+" "+SceneObject._objectCnt.toString();}
async init(){await this.createGeometry();await this.createShaders();await this.createRenderPipeline();await this.createComputePipeline();}
async createGeometry(){throw new Error("Method 'createGeometry()' must be implemented.");}
updateGeometry(){}
loadShader(filename){return new Promise((resolve,reject)=>{const xhttp=new XMLHttpRequest();xhttp.open("GET",filename);xhttp.setRequestHeader("Cache-Control","no-cache, no-store, max-age=0");xhttp.onload=function(){if(xhttp.readyState===XMLHttpRequest.DONE&&xhttp.status===200){resolve(xhttp.responseText);}
else{reject({status:xhttp.status,statusText:xhttp.statusText});}};xhttp.onerror=function(){reject({status:xhttp.status,statusText:xhttp.statusText});};xhttp.send();});}
async createShaders(){let shaderCode=await this.loadShader(this._shaderFile);this._shaderModule=this._device.createShaderModule({label:" Shader "+this.getName(),code:shaderCode,});}
async createRenderPipeline(){throw new Error("Method 'createRenderPipeline()' must be implemented.");}
render(pass){throw new Error("Method 'render(pass)' must be implemented.");}
async createComputePipeline(){throw new Error("Method 'createComputePipeline()' must be implemented.");}
compute(pass){throw new Error("Method 'compute(pass)' must be implemented.");}};class Standard2DVertexObject extends SceneObject{constructor(device,canvasFormat,vertices,shaderFile,topology){super(device,canvasFormat,shaderFile);this._vertices=vertices;this._topology=topology;}
async createGeometry(){this._vertexBuffer=this._device.createBuffer({label:"Vertices "+this.getName(),size:this._vertices.byteLength,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(this._vertexBuffer,0,this._vertices);this._vertexBufferLayout={arrayStride:6*Float32Array.BYTES_PER_ELEMENT,attributes:[{format:"float32x2",offset:0,shaderLocation:0,},{format:"float32x4",offset:2*Float32Array.BYTES_PER_ELEMENT,shaderLocation:1,}],};}
async createRenderPipeline(){this._renderPipeline=this._device.createRenderPipeline({label:"Render Pipeline "+this.getName(),layout:"auto",vertex:{module:this._shaderModule,entryPoint:"vertexMain",buffers:[this._vertexBufferLayout]},fragment:{module:this._shaderModule,entryPoint:"fragmentMain",targets:[{format:this._canvasFormat}]},primitive:{topology:this._topology}});}
render(pass){pass.setPipeline(this._renderPipeline);pass.setVertexBuffer(0,this._vertexBuffer);pass.draw(this._vertices.length/6);}
async createComputePipeline(){}
compute(pass){}}
class PolygonIO{constructor(){}
static readBinary(filename){return new Promise((resolve,reject)=>{const xhttp=new XMLHttpRequest();xhttp.open("GET",filename);xhttp.setRequestHeader("Cache-Control","no-cache, no-store, max-age=0");xhttp.responseType='arraybuffer';xhttp.onload=function(){if(xhttp.readyState===XMLHttpRequest.DONE&&xhttp.status===200){resolve(xhttp.response);}
else{reject(new Error('Error loading Polygon file: '+xhttp.status));}}
xhttp.onerror=function(){reject(new Error('Network error loading Polygon file'));}
xhttp.send();});}
static async read(filename){let binarydata=await PolygonIO.readBinary(filename);let text=new TextDecoder().decode(binarydata);const polygon=[];const lines=text.split('\n');const headers=lines[0].trim().split(',');for(let i=1;i<lines.length;++i){const line=lines[i].trim();if(line!=='')polygon.push(line.split(',').map(parseFloat));}
return polygon;}
static async write(polygon,filename){var data='';if(polygon[0].length==2)data='# x, y\n';else data='# x, y, z\n';for(let i=0;i<polygon.length;++i){data+=polygon[i].join(",")+'\n';}
const blob=new Blob([data],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='download.polygon';a.click();URL.revokeObjectURL(a.href);}}
class PGA2D{static geometricProduct(a,b){return[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0],a[0]*b[2]+a[1]*b[3]+a[2]*b[0]-a[3]*b[1],a[0]*b[3]-a[1]*b[2]+a[2]*b[1]+a[3]*b[0]];}
static reverse(a){return[a[0],-a[1],-a[2],-a[3]];}
static applyMotor(p,m){return PGA2D.geometricProduct(m,PGA2D.geometricProduct(p,PGA2D.reverse(m)));}
static motorNorm(m){return Math.sqrt(m[0]*m[0]+m[1]*m[1]+m[2]*m[2]+m[3]*m[3]);}
static createTranslator(dx,dy){return[1,0,-dx/2,-dy/2]}
static createRotor(angle,cx=0,cy=0){let p=PGA2D.createPoint(cx,cy);return[Math.cos(angle/2),Math.sin(angle/2)*p[1],Math.sin(angle/2)*p[2],Math.sin(angle/2)*p[3]];}
static createPoint(x,y){return[0,1,y,-x];}
static extractPoint(p){return[-p[3]/p[1],p[2]/p[1]];}
static normalizeMotor(m){let mnorm=PGA2D.motorNorm(m);if(mnorm==0.0){return[1,0,0,0];}
return[m[0]/mnorm,m[1]/mnorm,m[2]/mnorm,m[3]/mnorm];}
static applyMotorToPoint(p,m){let new_p=PGA2D.applyMotor(PGA2D.createPoint(p[0],p[1]),m);return PGA2D.extractPoint(new_p);};static isInside(v0,v1,p){const edge=PGA2D.createPoint(v1[0]-v0[0],v1[1]-v0[1]);const point=PGA2D.createPoint(p[0]-v0[0],p[1]-v0[1]);return(v1[0]-v0[0])*(p[1]-v0[1])-(v1[1]-v0[1])*(p[0]-v0[0])>0;}}
class Polygon{constructor(filename){this._filename=filename;}
centerOfMass(){let C=Array(this._dim).fill(0);for(let i=0;i<this._numV-1;++i){for(let j=0;j<this._dim;++j){C[j]+=this._polygon[i][j];}}
for(let i=0;i<this._dim;++i){C[i]/=this._numV;}
return C;}
surfaceArea(){const l=(a,b)=>Math.sqrt(Math.pow(b[0]-a[0],2)+Math.pow(b[1]-a[1],2)+Math.pow(b[2]-a[2],2));const area=(e0,e1,e2,s)=>Math.sqrt(s*(s-e0)*(s-e1)*(s-e2));let A=0;var v0=[...this.centerOfMass()];if(v0.length==2)v0.push(0);for(let i=0;i<this._polygon.length-1;++i){var v1=[...this._polygon[i]];if(v1.length==2)v1.push(0);var v2=[...this._polygon[i+1]];if(v2.length==2)v2.push(0);const e01=l(v0,v1);const e12=l(v1,v2);const e20=l(v2,v0);const s=(e01+e12+e20)/2;A+=area(e01,e12,e20,s);}
return A;}
normalizePolygon(){this._center=this.centerOfMass();for(let i=0;i<this._polygon.length;++i){for(let j=0;j<this._dim;++j){this._polygon[i][j]-=this._center[j];}}
this._area=this.surfaceArea();const targetArea=1;this._scaleFactor=Math.sqrt(1/this._area*targetArea);for(let i=0;i<this._polygon.length;++i){for(let j=0;j<this._dim;++j){this._polygon[i][j]*=this._scaleFactor;}}
if(Math.abs(this.surfaceArea()-targetArea)>0.0001){console.log("Something is wrong! The surface area is not as expected!");}}
refinePolygon(){var polygon=[];for(let i=0;i<this._polygon.length-1;++i){var v1=[...this._polygon[i]];var v2=[...this._polygon[i+1]];polygon.push(v1);let mid=Array(this._dim).fill(0);for(let j=0;j<this._dim;++j){mid[j]=(v1[j]+v2[j])/2;}
polygon.push(mid);}
polygon.push(this._polygon[0]);this._polygon=polygon;this._numV=this._polygon.length;this.normalizePolygon();}
reversePolygon(){var polygon=[];for(let i=this._polygon.length-1;i>=0;--i){polygon.push(this._polygon[i]);}
this._polygon=polygon;this._numV=this._polygon.length;this.normalizePolygon();}
isInside(v0,v1,p){if(this._polygon[0].length!=2)throw new Error("this formula works only for 2D Polygons.");return PGA2D.isInside(v0,v1,p);}
async init(){this._polygon=await PolygonIO.read(this._filename);this._numV=this._polygon.length;this._dim=this._polygon[0].length;this.normalizePolygon();}}
class PolygonObject extends Standard2DVertexObject{constructor(device,canvasFormat,shaderFile,filename,computeShaderFile=null){super(device,canvasFormat,null,shaderFile,"line-strip");this._polygon=new Polygon(filename);this._computeShaderFile=computeShaderFile;this._outside=true;}
async createGeometry(){await this._polygon.init();this._numV=this._polygon._numV;this._dim=this._polygon._dim;this._vertices=new Float32Array(this._numV*6);const polygonVertices=this._polygon._polygon;const color=[1.0,1.0,1.0,1.0];for(let i=0;i<this._numV;++i){this._vertices[i*6+0]=polygonVertices[i][0];this._vertices[i*6+1]=polygonVertices[i][1];this._vertices[i*6+2]=color[0];this._vertices[i*6+3]=color[1];this._vertices[i*6+4]=color[2];this._vertices[i*6+5]=color[3];}
await super.createGeometry();}
async createComputePipeline(){if(!this._computeShaderFile)return;const shaderCode=await this.loadShader(this._computeShaderFile);this._computeShaderModule=this._device.createShaderModule({label:'Winding Number Shader',code:shaderCode,});const numVertices=this._polygon._numV;this._mouseBuffer=this._device.createBuffer({size:8,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,});const positions=new Float32Array(numVertices*2);for(let i=0;i<numVertices;++i){positions[i*2]=this._polygon._polygon[i][0];positions[i*2+1]=this._polygon._polygon[i][1];}
this._vertexStorageBuffer=this._device.createBuffer({size:positions.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,});this._device.queue.writeBuffer(this._vertexStorageBuffer,0,positions);this._windingNumberBuffer=this._device.createBuffer({size:8,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC|GPUBufferUsage.COPY_DST,});this._stageBuffer=this._device.createBuffer({size:8,usage:GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST,});this._computePipeline=this._device.createComputePipeline({label:'Winding Number Pipeline',layout:'auto',compute:{module:this._computeShaderModule,entryPoint:'computeMain',},});this._computeBindGroup=this._device.createBindGroup({layout:this._computePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this._mouseBuffer}},{binding:1,resource:{buffer:this._vertexStorageBuffer}},{binding:2,resource:{buffer:this._windingNumberBuffer}},],});}
updateMousePos(x,y){if(!this._mouseBuffer)return;this._device.queue.writeBuffer(this._mouseBuffer,0,new Float32Array([x,y]));}
async computeWindingNumber(){if(!this._computePipeline)return this._outside;if(this._stageBuffer.mapState!="unmapped")return this._outside;this._device.queue.writeBuffer(this._windingNumberBuffer,0,new Int32Array([0,0]));const encoder=this._device.createCommandEncoder();const computePass=encoder.beginComputePass();computePass.setPipeline(this._computePipeline);computePass.setBindGroup(0,this._computeBindGroup);const numEdges=this._polygon._numV-1;computePass.dispatchWorkgroups(Math.ceil(numEdges/256));computePass.end();encoder.copyBufferToBuffer(this._windingNumberBuffer,0,this._stageBuffer,0,8);this._device.queue.submit([encoder.finish()]);await this._stageBuffer.mapAsync(GPUMapMode.READ);const windingNumber=new Int32Array(this._stageBuffer.getMappedRange());this._outside=windingNumber[0]==0||windingNumber[1]==0;this._stageBuffer.unmap();return this._outside;}};function cpuWindingNumber(polygon,numVertices,p){let windingPos=0;let windingNeg=0;for(let i=0;i<numVertices-1;++i){const v0=polygon[i];const v1=polygon[i+1];const minY=Math.min(v0[1],v1[1]);const maxY=Math.max(v0[1],v1[1]);if(p[1]<minY||p[1]>=maxY)continue;const t=(p[1]-v0[1])/(v1[1]-v0[1]);const xIntersect=v0[0]+t*(v1[0]-v0[0]);const cross=(v1[0]-v0[0])*(p[1]-v0[1])-(v1[1]-v0[1])*(p[0]-v0[0]);if(xIntersect>p[0]){windingPos+=cross>0?1:-1;}else if(xIntersect<p[0]){windingNeg+=cross>0?1:-1;}}
return windingPos!==0&&windingNeg!==0;}
async function init(){const canvasTag=document.createElement("canvas");canvasTag.id="renderCanvas";document.body.appendChild(canvasTag);const renderer=new Renderer(canvasTag);await renderer.init();renderer._clearColor={r:0.1,g:0.1,b:0.15,a:1.0};const polygonObj=new PolygonObject(renderer._device,renderer._canvasFormat,"./lib/Shaders/optimized_standard2d.wgsl","./assets/polygons/star.polygon","./lib/Shaders/optimized_winding_number.wgsl");await renderer.appendSceneObject(polygonObj);let fpsText=new StandardTextObject('fps: ??');let collisionText=new StandardTextObject('outside');collisionText.setPosition(10,60);let frameCnt=0;const frameInterval=1000/60;let lastCalled=Date.now();const renderFrame=()=>{const elapsed=Date.now()-lastCalled;if(elapsed>frameInterval){lastCalled=Date.now()-(elapsed%frameInterval);++frameCnt;renderer.render();}
requestAnimationFrame(renderFrame);};renderFrame();setInterval(()=>{fpsText.updateText('fps: '+frameCnt);frameCnt=0;},1000);window.addEventListener("mousemove",async(e)=>{const rect=canvasTag.getBoundingClientRect();const screenX=e.clientX-rect.left;const screenY=e.clientY-rect.top;const ndcX=(screenX/canvasTag.width)*2-1;const ndcY=-(screenY/canvasTag.height)*2+1;const mousePos=[ndcX,ndcY];let isInside;if(polygonObj._computePipeline){polygonObj.updateMousePos(ndcX,ndcY);const isOutside=await polygonObj.computeWindingNumber();isInside=!isOutside;}else{isInside=cpuWindingNumber(polygonObj._polygon._polygon,polygonObj._polygon._numV,mousePos);}
collisionText.updateText(isInside?'inside':'outside');});window.addEventListener("keydown",(e)=>{if(e.key==='f'||e.key==='F')fpsText.toggleVisibility();});return renderer;}
init().then((ret)=>{console.log(ret);}).catch((error)=>{const pTag=document.createElement("p");pTag.innerHTML=navigator.userAgent+"<br/>"+error.message;document.body.appendChild(pTag);document.getElementById("renderCanvas")?.remove();});